### ISSUE TITLE
Unable to connect to the Docker Remote API

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/postgresql-docker-boshrelease#21]
i get the following error

```
/var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/docker_manager.rb:268:in 
`rescue in validate_docker_remote_api': Unable to connect to the Docker Remote API `unix:///var/vcap/sys/run/docker/docker.sock': 
Connection refused - connect(2) for /var/vcap/sys/run/docker/docker.sock (Errno::ECONNREFUSED) (Exceptions::BackendError)
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/docker_manager.rb:258:in `validate_docker_remote_api'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/docker_manager.rb:20:in `initialize'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/plan.rb:67:in `new'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/plan.rb:67:in `build_container_manager'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/plan.rb:26:in `initialize'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/plan.rb:11:in `new'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/plan.rb:11:in `build'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/service.rb:11:in `block in build'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/service.rb:11:in `map'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/service.rb:11:in `build'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/catalog.rb:13:in `block in services'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/catalog.rb:13:in `map'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/catalog.rb:13:in `services'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/app/models/catalog.rb:21:in `plans'
        from /var/vcap/data/packages/cf-containers-broker/0876194f52cc409e4d55b4163f86910d8a2ade5d.1-ba7d9f71b4ba79ef935c221e3da147b32175fb55/lib/container_lifecycle.rb:10:in `update_all'
        from /var/vcap/packages/cf-containers-broker/bin/update_all_containers:7:in `<main>'
```

i noticed this error because the route never got registered
when i do

```
curl -L index.docker.io
```

i can connect to it.
any other suggestions?

**Comment by drnic** [comment]
To visit issues greater visibility and greater audience for
fixes/suggestions, perhaps raise docker-boshrelease specific issues at
https://github.com/cloudfoundry-community/docker-boshrelease/issues

**Comment by StanleyShen** [comment]
I think it because https://github.com/cloudfoundry-community/docker-boshrelease/issues/56 too if you are using the latest docker release.

https://github.com/cloudfoundry-community/postgresql-docker-boshrelease/issues/20
You can change the docker version to v23 and it should work for you.

**Comment by ramonskie** [comment]
changed the docker version to 23 and now it works as advertised :+1:
